apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ttc-vpa
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/RafaelBroseghini/cluster-addons.git
        revision: HEAD
        files:
          - path: "vpa/*/values.yaml"
  template:
    metadata:
      name: "ttc-vpa-{{path.basename}}"
    spec:
      project: default
      source:
        chart: vpa
        repoURL: https://charts.fairwinds.com/stable
        targetRevision: "{{helm.targetRevision}}"
        helm:
          values: |-
            {{values}}
      destination:
        server: "{{cluster.url}}"
        namespace: vpa
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
