apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ttc-vpa
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: dev
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: "ttc-vpa-{{cluster}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/RafaelBroseghini/cluster-addons.git
        targetRevision: HEAD
        path: vpa/environments/{{cluster}}
      destination:
        server: "{{url}}"
        namespace: vpa
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
